# dirs
display_name: train_model
dataset_path_dir: ["../../maniskill_inbin_formal.npy", "../../maniskill_outbin_formal.npy"]
models_save_dir: train_model
output_dir: train_model
# hyperparams
num_epochs: 300
num_diffusion_iters: 100
num_tests: 50
num_train_demos: 100
num_warmup_steps: 500
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 300
eval_epoch: 20
lr: 0.0001
weight_decay: 0.000001
batch_size: 64
resize_scale: 96
wandb: true
